export const menu = {
    restaurantId: 1,
    categories: [
        { id: 'a1', name: 'Starters' },
        { id: 'b2', name: 'Main' },
        { id: 'c3', name: 'Burgers' },
        { id: 'd4', name: 'Soups' },
        { id: 'e5', name: 'Dessert' },
        { id: 'f6', name: 'Drinks' },
    ],
    items: [
        {
            restaurantId: 1,
            categoryId: 'c3',
            item: {
                itemId: 1,
                itemName: 'Delicious Burger',
                discount: 0,
                isDisabled: false,
                itemPrice: 9.99,
                itemCalories: 800,
                itemImage: 'https://www.foodandwine.com/thmb/DI29Houjc_ccAtFKly0BbVsusHc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/crispy-comte-cheesburgers-FT-RECIPE0921-6166c6552b7148e8a8561f7765ddf20b.jpg',
                timeOfDay: ['All Day', 'Lunch'],
                itemProfileTastyTags: ['Spicy', 'Savory'],
                itemPortionSize: 'Large',
                itemPreparationTime: 20,
                itemLastingTime: 30,
                typeOfFoods: ['delivery only'],
                servingTemperature: 35,
                itemDietaryRestrictions: ['Vegetarian'],
                ingredients: [
                    { id: 1, restaurantId: 1, ingredientName: 'Beef Patty', unitOfStock: 'grams', quantity: 150, costPerUnit: 2.5, caloriesPerUnit: 200 },
                    { id: 2, restaurantId: 1, ingredientName: 'Cheddar Cheese', unitOfStock: 'slices', quantity: 2, costPerUnit: 1.5, caloriesPerUnit: 50 },
                    { id: 3, restaurantId: 1, ingredientName: 'Pickles', unitOfStock: 'pieces', quantity: 10, costPerUnit: 0.5, caloriesPerUnit: 5 },
                    { id: 4, restaurantId: 1, ingredientName: 'Tomato', unitOfStock: 'slices', quantity: 2, costPerUnit: 0.3, caloriesPerUnit: 10 },
                ],
                itemPackingType: 'Box',
                options: {
                    add: [
                        {
                            ingredientName: 'Cheese',
                            quantity: 1,
                            ingredient: { id: 4, restaurantId: 1, ingredientName: 'Swiss Cheese', unitOfStock: 'slices', quantity: 1, costPerUnit: 2, caloriesPerUnit: 60 },
                        },
                        {
                            ingredientName: 'Bacon',
                            quantity: 2,
                            ingredient: { id: 5, restaurantId: 1, ingredientName: 'Crispy Bacon', unitOfStock: 'slices', quantity: 2, costPerUnit: 1.8, caloriesPerUnit: 70 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Pickles',
                            quantity: 3,
                            ingredient: { id: 6, restaurantId: 1, ingredientName: 'Extra Pickles', unitOfStock: 'pieces', quantity: 5, costPerUnit: 0.3, caloriesPerUnit: 3 },
                        },
                        {
                            ingredientName: 'Onions',
                            quantity: 1,
                            ingredient: { id: 7, restaurantId: 1, ingredientName: 'Grilled Onions', unitOfStock: 'slices', quantity: 1, costPerUnit: 0.5, caloriesPerUnit: 20 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'a1',
            item: {
                itemId: 2,
                itemName: 'Crispy Spring Rolls',
                discount: 0,
                isDisabled: false,
                itemPrice: 5.99,
                itemCalories: 300,
                itemImage: 'https://www.sugarsaltmagic.com/wp-content/uploads/2023/01/Chinese-Spring-Rolls-4FEAT-500x500.jpg',
                timeOfDay: ['All Day', 'Dinner'],
                itemProfileTastyTags: ['Crispy', 'Vegetarian'],
                itemPortionSize: 'Medium',
                itemPreparationTime: 15,
                itemLastingTime: 25,
                typeOfFoods: ['eat only'],
                servingTemperature: 30,
                itemDietaryRestrictions: ['Vegetarian', 'Vegan'],
                ingredients: [
                    { id: 8, restaurantId: 1, ingredientName: 'Spring Roll Sheets', unitOfStock: 'pieces', quantity: 4, costPerUnit: 1.5, caloriesPerUnit: 75 },
                    { id: 9, restaurantId: 1, ingredientName: 'Mixed Vegetables', unitOfStock: 'cups', quantity: 1, costPerUnit: 2.0, caloriesPerUnit: 50 },
                    { id: 10, restaurantId: 1, ingredientName: 'Sweet Chili Sauce', unitOfStock: 'ounces', quantity: 2, costPerUnit: 0.8, caloriesPerUnit: 30 },
                ],
                itemPackingType: 'Plate',
                options: {
                    add: [
                        {
                            ingredientName: 'Soy Sauce',
                            quantity: 1,
                            ingredient: { id: 20, restaurantId: 1, ingredientName: 'Soy Sauce', unitOfStock: 'tablespoons', quantity: 1, costPerUnit: 0.5, caloriesPerUnit: 10 },
                        },
                        {
                            ingredientName: 'Sesame Seeds',
                            quantity: 1,
                            ingredient: { id: 21, restaurantId: 1, ingredientName: 'Sesame Seeds', unitOfStock: 'teaspoons', quantity: 1, costPerUnit: 0.3, caloriesPerUnit: 15 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Sweet Chili Sauce',
                            quantity: 1,
                            ingredient: { id: 22, restaurantId: 1, ingredientName: 'Extra Sweet Chili Sauce', unitOfStock: 'ounces', quantity: 1, costPerUnit: 0.5, caloriesPerUnit: 30 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'b2',
            item: {
                itemId: 3,
                itemName: 'Grilled Salmon',
                discount: 10,
                isDisabled: false,
                itemPrice: 14.99,
                itemCalories: 450,
                itemImage: 'https://www.wholesomeyum.com/wp-content/uploads/2021/06/wholesomeyum-Grilled-Salmon-Recipe-8.jpg',
                timeOfDay: ['Dinner'],
                itemProfileTastyTags: ['Healthy', 'Seafood'],
                itemPortionSize: 'Large',
                itemPreparationTime: 25,
                itemLastingTime: 35,
                typeOfFoods: ['eat only'],
                servingTemperature: 62,
                itemDietaryRestrictions: ['Pescatarian'],
                ingredients: [
                    { id: 11, restaurantId: 1, ingredientName: 'Salmon Fillet', unitOfStock: 'ounces', quantity: 8, costPerUnit: 3.5, caloriesPerUnit: 150 },
                    { id: 12, restaurantId: 1, ingredientName: 'Lemon', unitOfStock: 'slices', quantity: 2, costPerUnit: 0.5, caloriesPerUnit: 10 },
                    { id: 13, restaurantId: 1, ingredientName: 'Olive Oil', unitOfStock: 'tablespoons', quantity: 1, costPerUnit: 0.7, caloriesPerUnit: 60 },
                ],
                itemPackingType: 'Plate',
                options: {
                    add: [
                        {
                            ingredientName: 'Garlic Butter',
                            quantity: 1,
                            ingredient: { id: 23, restaurantId: 1, ingredientName: 'Garlic Butter', unitOfStock: 'tablespoons', quantity: 1, costPerUnit: 0.8, caloriesPerUnit: 50 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Lemon',
                            quantity: 1,
                            ingredient: { id: 24, restaurantId: 1, ingredientName: 'Extra Lemon', unitOfStock: 'slices', quantity: 1, costPerUnit: 0.3, caloriesPerUnit: 5 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'd4',
            item: {
                itemId: 4,
                itemName: 'Creamy Tomato Soup',
                discount: 0,
                isDisabled: false,
                itemPrice: 6.99,
                itemCalories: 250,
                itemImage: 'https://www.allrecipes.com/thmb/QijITeBBcE99Ur5kDoccAJ35WWo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/277311spicy-fresh-tomato-soupFranceC4x3-56454ad082214f33960f62665fc8c169.jpg',
                timeOfDay: ['All Day', 'Lunch'],
                itemProfileTastyTags: ['Creamy', 'Comfort Food'],
                itemPortionSize: 'Medium',
                itemPreparationTime: 18,
                itemLastingTime: 28,
                typeOfFoods: ['eat only', 'pickup only'],
                servingTemperature: 42,
                itemDietaryRestrictions: ['Vegetarian'],
                ingredients: [
                    { id: 14, restaurantId: 1, ingredientName: 'Tomatoes', unitOfStock: 'cups', quantity: 2, costPerUnit: 1.0, caloriesPerUnit: 30 },
                    { id: 15, restaurantId: 1, ingredientName: 'Heavy Cream', unitOfStock: 'ounces', quantity: 4, costPerUnit: 2.0, caloriesPerUnit: 120 },
                    { id: 16, restaurantId: 1, ingredientName: 'Onion', unitOfStock: 'pieces', quantity: 1, costPerUnit: 0.3, caloriesPerUnit: 15 },
                ],
                itemPackingType: 'Bowl',
                options: {
                    add: [
                        {
                            ingredientName: 'Croutons',
                            quantity: 1,
                            ingredient: { id: 22, restaurantId: 1, ingredientName: 'Garlic Croutons', unitOfStock: 'pieces', quantity: 6, costPerUnit: 0.5, caloriesPerUnit: 15 },
                        },
                        {
                            ingredientName: 'Basil',
                            quantity: 1,
                            ingredient: { id: 23, restaurantId: 1, ingredientName: 'Fresh Basil Leaves', unitOfStock: 'leaves', quantity: 3, costPerUnit: 0.3, caloriesPerUnit: 5 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Heavy Cream',
                            quantity: 1,
                            ingredient: { id: 24, restaurantId: 1, ingredientName: 'Reduced Fat Cream', unitOfStock: 'ounces', quantity: 4, costPerUnit: 1.5, caloriesPerUnit: 80 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'e5',
            item: {
                itemId: 5,
                itemName: 'Chocolate Lava Cake',
                discount: 0,
                isDisabled: true,
                itemPrice: 8.99,
                itemCalories: 500,
                itemImage: 'https://www.foodandwine.com/thmb/XdFd-DvTtouryLCjeCqwhfmmK-A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/molten-chocolate-cake-FT-RECIPE0220-0a33d7d0ab0c45588f7bfe742d33a9bc.jpg',
                timeOfDay: ['Dinner'],
                itemProfileTastyTags: ['Decadent', 'Sweet Tooth'],
                itemPortionSize: 'Small',
                itemPreparationTime: 22,
                itemLastingTime: 25,
                typeOfFoods: ['eat only'],
                servingTemperature: 31,
                itemDietaryRestrictions: ['Vegetarian'],
                ingredients: [
                    { id: 17, restaurantId: 1, ingredientName: 'Chocolate', unitOfStock: 'ounces', quantity: 3, costPerUnit: 1.5, caloriesPerUnit: 150 },
                    { id: 18, restaurantId: 1, ingredientName: 'Butter', unitOfStock: 'tablespoons', quantity: 2, costPerUnit: 0.8, caloriesPerUnit: 100 },
                    { id: 19, restaurantId: 1, ingredientName: 'Sugar', unitOfStock: 'tablespoons', quantity: 3, costPerUnit: 0.5, caloriesPerUnit: 50 },
                ],
                itemPackingType: 'Plate',
                options: {
                    add: [
                        {
                            ingredientName: 'Vanilla Ice Cream',
                            quantity: 1,
                            ingredient: { id: 25, restaurantId: 1, ingredientName: 'Vanilla Ice Cream Scoop', unitOfStock: 'scoops', quantity: 1, costPerUnit: 1.0, caloriesPerUnit: 80 },
                        },
                        {
                            ingredientName: 'Berries',
                            quantity: 1,
                            ingredient: { id: 26, restaurantId: 1, ingredientName: 'Mixed Berries', unitOfStock: 'cups', quantity: 1, costPerUnit: 2.5, caloriesPerUnit: 30 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Sugar',
                            quantity: 1,
                            ingredient: { id: 27, restaurantId: 1, ingredientName: 'Sugar-Free Sweetener', unitOfStock: 'tablespoons', quantity: 3, costPerUnit: 0.8, caloriesPerUnit: 20 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'b2',
            item: {
                itemId: 6,
                itemName: 'Grilled Chicken Salad',
                discount: 0,
                isDisabled: false,
                itemPrice: 10.99,
                itemCalories: 350,
                itemImage: '',
                timeOfDay: ['Lunch', 'Dinner'],
                itemProfileTastyTags: ['Healthy', 'Fresh'],
                itemPortionSize: 'Medium',
                itemPreparationTime: 15,
                itemLastingTime: 25,
                typeOfFoods: ['eat only', 'pickup only'],
                servingTemperature: 14,
                itemDietaryRestrictions: ['Gluten-Free'],
                ingredients: [
                    { id: 28, restaurantId: 1, ingredientName: 'Chicken Breast', unitOfStock: 'ounces', quantity: 6, costPerUnit: 2.5, caloriesPerUnit: 180 },
                    { id: 29, restaurantId: 1, ingredientName: 'Mixed Greens', unitOfStock: 'cups', quantity: 2, costPerUnit: 1.0, caloriesPerUnit: 20 },
                    { id: 30, restaurantId: 1, ingredientName: 'Cherry Tomatoes', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.5, caloriesPerUnit: 15 },
                    { id: 31, restaurantId: 1, ingredientName: 'Balsamic Vinaigrette', unitOfStock: 'ounces', quantity: 2, costPerUnit: 1.2, caloriesPerUnit: 40 },
                ],
                itemPackingType: 'Bowl',
                options: {
                    add: [
                        {
                            ingredientName: 'Avocado',
                            quantity: 1,
                            ingredient: { id: 32, restaurantId: 1, ingredientName: 'Sliced Avocado', unitOfStock: 'slices', quantity: 4, costPerUnit: 1.8, caloriesPerUnit: 50 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Balsamic Vinaigrette',
                            quantity: 1,
                            ingredient: { id: 33, restaurantId: 1, ingredientName: 'Ranch Dressing', unitOfStock: 'ounces', quantity: 2, costPerUnit: 1.5, caloriesPerUnit: 60 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'c3',
            item: {
                itemId: 7,
                itemName: 'Margherita Pizza',
                discount: 0,
                isDisabled: false,
                itemPrice: 12.99,
                itemCalories: 800,
                itemImage: '',
                timeOfDay: ['All Day', 'Dinner'],
                itemProfileTastyTags: ['Classic', 'Vegetarian'],
                itemPortionSize: 'Large',
                itemPreparationTime: 25,
                itemLastingTime: 30,
                typeOfFoods: ['delivery only', 'eat only'],
                servingTemperature: 44,
                itemDietaryRestrictions: ['Vegetarian'],
                ingredients: [
                    { id: 34, restaurantId: 1, ingredientName: 'Pizza Dough', unitOfStock: 'grams', quantity: 300, costPerUnit: 2.0, caloriesPerUnit: 150 },
                    { id: 35, restaurantId: 1, ingredientName: 'Tomato Sauce', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.5, caloriesPerUnit: 30 },
                    { id: 36, restaurantId: 1, ingredientName: 'Fresh Mozzarella', unitOfStock: 'ounces', quantity: 8, costPerUnit: 3.0, caloriesPerUnit: 200 },
                    { id: 37, restaurantId: 1, ingredientName: 'Fresh Basil Leaves', unitOfStock: 'leaves', quantity: 5, costPerUnit: 0.8, caloriesPerUnit: 10 },
                ],
                itemPackingType: 'Box',
                options: {
                    add: [
                        {
                            ingredientName: 'Cherry Tomatoes',
                            quantity: 1,
                            ingredient: { id: 38, restaurantId: 1, ingredientName: 'Sliced Cherry Tomatoes', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.2, caloriesPerUnit: 15 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Fresh Basil Leaves',
                            quantity: 2,
                            ingredient: { id: 39, restaurantId: 1, ingredientName: 'Extra Fresh Basil', unitOfStock: 'leaves', quantity: 3, costPerUnit: 0.5, caloriesPerUnit: 5 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'b2',
            item: {
                itemId: 8,
                itemName: 'Classic Caesar Salad',
                discount: 0,
                isDisabled: false,
                itemPrice: 8.99,
                itemCalories: 450,
                itemImage: '',
                timeOfDay: ['Lunch', 'Dinner'],
                itemProfileTastyTags: ['Classic', 'Savory'],
                itemPortionSize: 'Medium',
                itemPreparationTime: 15,
                itemLastingTime: 25,
                typeOfFoods: ['eat only', 'pickup only'],
                servingTemperature: 19,
                itemDietaryRestrictions: ['Vegetarian'],
                ingredients: [
                    { id: 40, restaurantId: 1, ingredientName: 'Romaine Lettuce', unitOfStock: 'cups', quantity: 2, costPerUnit: 1.0, caloriesPerUnit: 10 },
                    { id: 41, restaurantId: 1, ingredientName: 'Caesar Dressing', unitOfStock: 'ounces', quantity: 2, costPerUnit: 1.2, caloriesPerUnit: 100 },
                    { id: 42, restaurantId: 1, ingredientName: 'Croutons', unitOfStock: 'pieces', quantity: 6, costPerUnit: 0.5, caloriesPerUnit: 30 },
                    { id: 43, restaurantId: 1, ingredientName: 'Parmesan Cheese', unitOfStock: 'tablespoons', quantity: 2, costPerUnit: 1.5, caloriesPerUnit: 50 },
                ],
                itemPackingType: 'Bowl',
                options: {
                    add: [
                        {
                            ingredientName: 'Grilled Chicken',
                            quantity: 1,
                            ingredient: { id: 44, restaurantId: 1, ingredientName: 'Grilled Chicken Strips', unitOfStock: 'ounces', quantity: 4, costPerUnit: 3.0, caloriesPerUnit: 180 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Croutons',
                            quantity: 2,
                            ingredient: { id: 45, restaurantId: 1, ingredientName: 'Extra Croutons', unitOfStock: 'pieces', quantity: 4, costPerUnit: 0.3, caloriesPerUnit: 20 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'b2',
            item: {
                itemId: 9,
                itemName: 'Spaghetti Bolognese',
                discount: 0,
                isDisabled: false,
                itemPrice: 12.99,
                itemCalories: 600,
                itemImage: '',
                timeOfDay: ['All Day', 'Dinner'],
                itemProfileTastyTags: ['Hearty', 'Italian'],
                itemPortionSize: 'Large',
                itemPreparationTime: 30,
                itemLastingTime: 35,
                typeOfFoods: ['delivery only', 'eat only'],
                servingTemperature: 32,
                itemDietaryRestrictions: [],
                ingredients: [
                    { id: 46, restaurantId: 1, ingredientName: 'Ground Beef', unitOfStock: 'ounces', quantity: 8, costPerUnit: 4.0, caloriesPerUnit: 400 },
                    { id: 47, restaurantId: 1, ingredientName: 'Tomato Sauce', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.5, caloriesPerUnit: 30 },
                    { id: 48, restaurantId: 1, ingredientName: 'Onion', unitOfStock: 'pieces', quantity: 1, costPerUnit: 0.5, caloriesPerUnit: 15 },
                    { id: 49, restaurantId: 1, ingredientName: 'Garlic', unitOfStock: 'cloves', quantity: 2, costPerUnit: 0.3, caloriesPerUnit: 5 },
                    { id: 50, restaurantId: 1, ingredientName: 'Spaghetti', unitOfStock: 'ounces', quantity: 6, costPerUnit: 1.0, caloriesPerUnit: 150 },
                ],
                itemPackingType: 'Box',
                options: {
                    add: [
                        {
                            ingredientName: 'Parmesan Cheese',
                            quantity: 1,
                            ingredient: { id: 51, restaurantId: 1, ingredientName: 'Grated Parmesan Cheese', unitOfStock: 'tablespoons', quantity: 2, costPerUnit: 1.5, caloriesPerUnit: 50 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Onion',
                            quantity: 1,
                            ingredient: { id: 52, restaurantId: 1, ingredientName: 'Extra Onion', unitOfStock: 'pieces', quantity: 1, costPerUnit: 0.3, caloriesPerUnit: 15 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'b2',
            item: {
                itemId: 10,
                itemName: 'Chicken Alfredo Pasta',
                discount: 0,
                isDisabled: false,
                itemPrice: 14.99,
                itemCalories: 700,
                itemImage: '',
                timeOfDay: ['All Day', 'Dinner'],
                itemProfileTastyTags: ['Creamy', 'Italian'],
                itemPortionSize: 'Large',
                itemPreparationTime: 25,
                itemLastingTime: 30,
                typeOfFoods: ['delivery only', 'eat only'],
                servingTemperature: 42,
                itemDietaryRestrictions: [],
                ingredients: [
                    { id: 53, restaurantId: 1, ingredientName: 'Chicken Breast', unitOfStock: 'ounces', quantity: 8, costPerUnit: 4.5, caloriesPerUnit: 200 },
                    { id: 54, restaurantId: 1, ingredientName: 'Fettuccine Pasta', unitOfStock: 'ounces', quantity: 6, costPerUnit: 1.2, caloriesPerUnit: 180 },
                    { id: 55, restaurantId: 1, ingredientName: 'Heavy Cream', unitOfStock: 'ounces', quantity: 4, costPerUnit: 2.0, caloriesPerUnit: 120 },
                    { id: 56, restaurantId: 1, ingredientName: 'Parmesan Cheese', unitOfStock: 'tablespoons', quantity: 2, costPerUnit: 1.5, caloriesPerUnit: 50 },
                    { id: 57, restaurantId: 1, ingredientName: 'Garlic', unitOfStock: 'cloves', quantity: 2, costPerUnit: 0.3, caloriesPerUnit: 5 },
                ],
                itemPackingType: 'Box',
                options: {
                    add: [
                        {
                            ingredientName: 'Broccoli',
                            quantity: 1,
                            ingredient: { id: 58, restaurantId: 1, ingredientName: 'Steamed Broccoli Florets', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.2, caloriesPerUnit: 30 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Heavy Cream',
                            quantity: 1,
                            ingredient: { id: 59, restaurantId: 1, ingredientName: 'Reduced Fat Cream', unitOfStock: 'ounces', quantity: 4, costPerUnit: 1.5, caloriesPerUnit: 80 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'b2',
            item: {
                itemId: 11,
                itemName: 'Beef Stir-Fry',
                discount: 0,
                isDisabled: false,
                itemPrice: 11.99,
                itemCalories: 550,
                itemImage: '',
                timeOfDay: ['All Day', 'Dinner'],
                itemProfileTastyTags: ['Asian', 'Stir-Fry'],
                itemPortionSize: 'Medium',
                itemPreparationTime: 20,
                itemLastingTime: 25,
                typeOfFoods: ['delivery only', 'eat only'],
                servingTemperature: 54,
                itemDietaryRestrictions: [],
                ingredients: [
                    { id: 60, restaurantId: 1, ingredientName: 'Beef Strips', unitOfStock: 'ounces', quantity: 8, costPerUnit: 4.0, caloriesPerUnit: 400 },
                    { id: 61, restaurantId: 1, ingredientName: 'Mixed Vegetables', unitOfStock: 'cups', quantity: 2, costPerUnit: 2.0, caloriesPerUnit: 50 },
                    { id: 62, restaurantId: 1, ingredientName: 'Soy Sauce', unitOfStock: 'ounces', quantity: 2, costPerUnit: 1.0, caloriesPerUnit: 20 },
                    { id: 63, restaurantId: 1, ingredientName: 'Sesame Oil', unitOfStock: 'teaspoons', quantity: 1, costPerUnit: 1.5, caloriesPerUnit: 30 },
                    { id: 64, restaurantId: 1, ingredientName: 'Garlic', unitOfStock: 'cloves', quantity: 2, costPerUnit: 0.3, caloriesPerUnit: 5 },
                ],
                itemPackingType: 'Box',
                options: {
                    add: [
                        {
                            ingredientName: 'Brown Rice',
                            quantity: 1,
                            ingredient: { id: 65, restaurantId: 1, ingredientName: 'Steamed Brown Rice', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.2, caloriesPerUnit: 100 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Soy Sauce',
                            quantity: 1,
                            ingredient: { id: 66, restaurantId: 1, ingredientName: 'Low Sodium Soy Sauce', unitOfStock: 'ounces', quantity: 2, costPerUnit: 1.2, caloriesPerUnit: 15 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'a1',
            item: {
                itemId: 12,
                itemName: 'Garlic Parmesan Wings',
                discount: 0,
                isDisabled: false,
                itemPrice: 9.99,
                itemCalories: 450,
                itemImage: '',
                timeOfDay: ['All Day', 'Dinner'],
                itemProfileTastyTags: ['Savory', 'Appetizer'],
                itemPortionSize: 'Medium',
                itemPreparationTime: 20,
                itemLastingTime: 30,
                typeOfFoods: ['eat only', 'pickup only'],
                servingTemperature: 33,
                itemDietaryRestrictions: [],
                ingredients: [
                    { id: 67, restaurantId: 1, ingredientName: 'Chicken Wings', unitOfStock: 'pieces', quantity: 8, costPerUnit: 2.0, caloriesPerUnit: 100 },
                    { id: 68, restaurantId: 1, ingredientName: 'Garlic Parmesan Sauce', unitOfStock: 'ounces', quantity: 2, costPerUnit: 1.5, caloriesPerUnit: 120 },
                    { id: 69, restaurantId: 1, ingredientName: 'Celery Sticks', unitOfStock: 'sticks', quantity: 4, costPerUnit: 0.5, caloriesPerUnit: 10 },
                    { id: 70, restaurantId: 1, ingredientName: 'Blue Cheese Dressing', unitOfStock: 'ounces', quantity: 2, costPerUnit: 1.2, caloriesPerUnit: 80 },
                ],
                itemPackingType: 'Basket',
                options: {
                    add: [
                        {
                            ingredientName: 'Carrot Sticks',
                            quantity: 1,
                            ingredient: { id: 71, restaurantId: 1, ingredientName: 'Carrot Sticks', unitOfStock: 'sticks', quantity: 4, costPerUnit: 0.5, caloriesPerUnit: 15 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Blue Cheese Dressing',
                            quantity: 1,
                            ingredient: { id: 72, restaurantId: 1, ingredientName: 'Ranch Dressing', unitOfStock: 'ounces', quantity: 2, costPerUnit: 1.5, caloriesPerUnit: 90 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'a1',
            item: {
                itemId: 13,
                itemName: 'Spinach and Artichoke Dip',
                discount: 0,
                isDisabled: false,
                itemPrice: 7.99,
                itemCalories: 320,
                itemImage: '',
                timeOfDay: ['All Day', 'Breakfast'],
                itemProfileTastyTags: ['Creamy', 'Appetizer'],
                itemPortionSize: 'Small',
                itemPreparationTime: 15,
                itemLastingTime: 25,
                typeOfFoods: ['eat only', 'pickup only'],
                servingTemperature: 23,
                itemDietaryRestrictions: ['Vegetarian'],
                ingredients: [
                    { id: 73, restaurantId: 1, ingredientName: 'Spinach', unitOfStock: 'ounces', quantity: 4, costPerUnit: 1.0, caloriesPerUnit: 40 },
                    { id: 74, restaurantId: 1, ingredientName: 'Artichoke Hearts', unitOfStock: 'ounces', quantity: 4, costPerUnit: 2.0, caloriesPerUnit: 80 },
                    { id: 75, restaurantId: 1, ingredientName: 'Cream Cheese', unitOfStock: 'ounces', quantity: 4, costPerUnit: 1.5, caloriesPerUnit: 120 },
                    { id: 76, restaurantId: 1, ingredientName: 'Parmesan Cheese', unitOfStock: 'tablespoons', quantity: 2, costPerUnit: 1.5, caloriesPerUnit: 50 },
                ],
                itemPackingType: 'Bowl',
                options: {
                    add: [
                        {
                            ingredientName: 'Tortilla Chips',
                            quantity: 1,
                            ingredient: { id: 77, restaurantId: 1, ingredientName: 'Tortilla Chips', unitOfStock: 'ounces', quantity: 4, costPerUnit: 1.2, caloriesPerUnit: 100 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Cream Cheese',
                            quantity: 1,
                            ingredient: { id: 78, restaurantId: 1, ingredientName: 'Low-Fat Cream Cheese', unitOfStock: 'ounces', quantity: 4, costPerUnit: 1.8, caloriesPerUnit: 90 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'e5',
            item: {
                itemId: 14,
                itemName: 'Mango Sorbet',
                discount: 0,
                isDisabled: false,
                itemPrice: 5.99,
                itemCalories: 180,
                itemImage: '',
                timeOfDay: ['All Day'],
                itemProfileTastyTags: ['Refreshing', 'Fruity'],
                itemPortionSize: 'Small',
                itemPreparationTime: 10,
                itemLastingTime: 20,
                typeOfFoods: ['eat only', 'pickup only'],
                servingTemperature: 5,
                itemDietaryRestrictions: ['Vegan', 'Gluten-Free'],
                ingredients: [
                    { id: 79, restaurantId: 1, ingredientName: 'Mango Puree', unitOfStock: 'ounces', quantity: 6, costPerUnit: 2.0, caloriesPerUnit: 120 },
                    { id: 80, restaurantId: 1, ingredientName: 'Sugar', unitOfStock: 'tablespoons', quantity: 2, costPerUnit: 0.5, caloriesPerUnit: 40 },
                    { id: 81, restaurantId: 1, ingredientName: 'Lime Juice', unitOfStock: 'tablespoons', quantity: 1, costPerUnit: 0.3, caloriesPerUnit: 20 },
                ],
                itemPackingType: 'Cup',
                options: {
                    add: [
                        {
                            ingredientName: 'Fresh Mint',
                            quantity: 1,
                            ingredient: { id: 82, restaurantId: 1, ingredientName: 'Fresh Mint Leaves', unitOfStock: 'leaves', quantity: 4, costPerUnit: 0.2, caloriesPerUnit: 5 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Sugar',
                            quantity: 1,
                            ingredient: { id: 83, restaurantId: 1, ingredientName: 'Sugar Substitute', unitOfStock: 'tablespoons', quantity: 2, costPerUnit: 0.8, caloriesPerUnit: 40 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'e5',
            item: {
                itemId: 15,
                itemName: 'Tiramisu',
                discount: 0,
                isDisabled: false,
                itemPrice: 7.99,
                itemCalories: 400,
                itemImage: '',
                timeOfDay: ['Dinner'],
                itemProfileTastyTags: ['Decadent', 'Italian'],
                itemPortionSize: 'Medium',
                itemPreparationTime: 20,
                itemLastingTime: 30,
                typeOfFoods: ['eat only', 'pickup only'],
                servingTemperature: 12,
                itemDietaryRestrictions: [],
                ingredients: [
                    { id: 84, restaurantId: 1, ingredientName: 'Ladyfingers', unitOfStock: 'pieces', quantity: 6, costPerUnit: 1.0, caloriesPerUnit: 120 },
                    { id: 85, restaurantId: 1, ingredientName: 'Mascarpone Cheese', unitOfStock: 'ounces', quantity: 4, costPerUnit: 3.0, caloriesPerUnit: 200 },
                    { id: 86, restaurantId: 1, ingredientName: 'Espresso', unitOfStock: 'ounces', quantity: 2, costPerUnit: 0.5, caloriesPerUnit: 10 },
                    { id: 87, restaurantId: 1, ingredientName: 'Cocoa Powder', unitOfStock: 'teaspoons', quantity: 1, costPerUnit: 0.3, caloriesPerUnit: 20 },
                ],
                itemPackingType: 'Plate',
                options: {
                    add: [
                        {
                            ingredientName: 'Chocolate Shavings',
                            quantity: 1,
                            ingredient: { id: 88, restaurantId: 1, ingredientName: 'Chocolate Shavings', unitOfStock: 'tablespoons', quantity: 1, costPerUnit: 1.5, caloriesPerUnit: 50 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Espresso',
                            quantity: 1,
                            ingredient: { id: 89, restaurantId: 1, ingredientName: 'Decaffeinated Coffee', unitOfStock: 'ounces', quantity: 2, costPerUnit: 0.8, caloriesPerUnit: 5 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'a1',
            item: {
                itemId: 16,
                itemName: 'Mediterranean Platter',
                discount: 0,
                isDisabled: false,
                itemPrice: 13.99,
                itemCalories: 550,
                itemImage: '',
                timeOfDay: ['All Day', 'Lunch'],
                itemProfileTastyTags: ['Fresh', 'Mediterranean'],
                itemPortionSize: 'Sharing',
                itemPreparationTime: 15,
                itemLastingTime: 40,
                typeOfFoods: ['eat only', 'pickup only'],
                servingTemperature: 18,
                itemDietaryRestrictions: ['Vegetarian'],
                ingredients: [
                    { id: 96, restaurantId: 1, ingredientName: 'Hummus', unitOfStock: 'ounces', quantity: 4, costPerUnit: 2.0, caloriesPerUnit: 200 },
                    { id: 97, restaurantId: 1, ingredientName: 'Tzatziki', unitOfStock: 'ounces', quantity: 4, costPerUnit: 1.5, caloriesPerUnit: 100 },
                    { id: 98, restaurantId: 1, ingredientName: 'Kalamata Olives', unitOfStock: 'ounces', quantity: 2, costPerUnit: 2.5, caloriesPerUnit: 120 },
                    { id: 99, restaurantId: 1, ingredientName: 'Feta Cheese', unitOfStock: 'ounces', quantity: 3, costPerUnit: 3.0, caloriesPerUnit: 150 },
                    { id: 100, restaurantId: 1, ingredientName: 'Cucumber Slices', unitOfStock: 'ounces', quantity: 3, costPerUnit: 1.0, caloriesPerUnit: 30 },
                ],
                itemPackingType: 'Platter',
                options: {
                    add: [
                        {
                            ingredientName: 'Pita Bread',
                            quantity: 1,
                            ingredient: { id: 101, restaurantId: 1, ingredientName: 'Pita Bread', unitOfStock: 'pieces', quantity: 4, costPerUnit: 0.5, caloriesPerUnit: 80 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Feta Cheese',
                            quantity: 1,
                            ingredient: { id: 102, restaurantId: 1, ingredientName: 'Vegan Feta', unitOfStock: 'ounces', quantity: 3, costPerUnit: 4.0, caloriesPerUnit: 180 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'b2',
            item: {
                itemId: 17,
                itemName: 'Teriyaki Salmon Bowl',
                discount: 0,
                isDisabled: false,
                itemPrice: 15.99,
                itemCalories: 700,
                itemImage: '',
                timeOfDay: ['All Day', 'Dinner'],
                itemProfileTastyTags: ['Asian', 'Healthy'],
                itemPortionSize: 'Regular',
                itemPreparationTime: 30,
                itemLastingTime: 35,
                typeOfFoods: ['delivery only', 'eat only'],
                servingTemperature: 25,
                itemDietaryRestrictions: [],
                ingredients: [
                    { id: 103, restaurantId: 1, ingredientName: 'Salmon Fillet', unitOfStock: 'ounces', quantity: 6, costPerUnit: 5.0, caloriesPerUnit: 300 },
                    { id: 104, restaurantId: 1, ingredientName: 'Teriyaki Sauce', unitOfStock: 'ounces', quantity: 2, costPerUnit: 2.0, caloriesPerUnit: 100 },
                    { id: 105, restaurantId: 1, ingredientName: 'Brown Rice', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.0, caloriesPerUnit: 200 },
                    { id: 106, restaurantId: 1, ingredientName: 'Broccoli', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.5, caloriesPerUnit: 50 },
                    { id: 107, restaurantId: 1, ingredientName: 'Carrots', unitOfStock: 'ounces', quantity: 3, costPerUnit: 1.2, caloriesPerUnit: 40 },
                ],
                itemPackingType: 'Bowl',
                options: {
                    add: [
                        {
                            ingredientName: 'Avocado Slices',
                            quantity: 1,
                            ingredient: { id: 108, restaurantId: 1, ingredientName: 'Avocado Slices', unitOfStock: 'pieces', quantity: 4, costPerUnit: 2.0, caloriesPerUnit: 100 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Brown Rice',
                            quantity: 1,
                            ingredient: { id: 109, restaurantId: 1, ingredientName: 'Quinoa', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.5, caloriesPerUnit: 150 },
                        },
                    ],
                },
            },
        },
        {
            restaurantId: 1,
            categoryId: 'f6',
            item: {
                itemId: 18,
                itemName: 'Berry Blast Smoothie',
                discount: 0,
                isDisabled: false,
                itemPrice: 6.49,
                itemCalories: 220,
                itemImage: '',
                timeOfDay: ['All Day', 'Breakfast'],
                itemProfileTastyTags: ['Refreshing', 'Fruity'],
                itemPortionSize: 'Medium',
                itemPreparationTime: 10,
                itemLastingTime: 20,
                typeOfFoods: ['eat only', 'pickup only'],
                servingTemperature: 10,
                itemDietaryRestrictions: ['Vegan'],
                ingredients: [
                    { id: 110, restaurantId: 1, ingredientName: 'Mixed Berries', unitOfStock: 'cups', quantity: 1, costPerUnit: 2.0, caloriesPerUnit: 50 },
                    { id: 111, restaurantId: 1, ingredientName: 'Banana', unitOfStock: 'pieces', quantity: 1, costPerUnit: 0.5, caloriesPerUnit: 100 },
                    { id: 112, restaurantId: 1, ingredientName: 'Almond Milk', unitOfStock: 'cups', quantity: 1, costPerUnit: 1.5, caloriesPerUnit: 70 },
                    { id: 113, restaurantId: 1, ingredientName: 'Greek Yogurt', unitOfStock: 'tablespoons', quantity: 2, costPerUnit: 1.0, caloriesPerUnit: 0 },
                ],
                itemPackingType: 'Cup',
                options: {
                    add: [
                        {
                            ingredientName: 'Chia Seeds',
                            quantity: 1,
                            ingredient: { id: 114, restaurantId: 1, ingredientName: 'Chia Seeds', unitOfStock: 'tablespoons', quantity: 1, costPerUnit: 0.3, caloriesPerUnit: 20 },
                        },
                    ],
                    no: [
                        {
                            ingredientName: 'Greek Yogurt',
                            quantity: 1,
                            ingredient: { id: 115, restaurantId: 1, ingredientName: 'Coconut Milk', unitOfStock: 'cups', quantity: 1, costPerUnit: 2.0, caloriesPerUnit: 90 },
                        },
                    ],
                },
            },
        },
        //Add more here                                                                                                      
    ],
};
